### ISSUE TITLE
پایتون ۳ و جنگو ۲

### ISSUE THREAD

**Issue by m69fard** [par3ae/Django-Zarinpal#1]
سلام
آیا پایتون ۳ و جنگو ۲ از این روش پشتیبانی میکنن؟

**Comment by rasooll** [comment]
برای استفاده از ماژول
`suds`
حتما باید از پایتون ۲ استفاده کنید.

**Comment by par3ae** [comment]
> برای استفاده از ماژول
> `suds`
> حتما باید از پایتون ۲ استفاده کنید.

باسلام و احترام
به کمک دستور زیر میتوانید از ماژول فوق در پایتون3 هم استفاده کنید
pip3 install suds-py3
